# Generated by Django 5.2.17 on 2026-08-06 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable identifier used in URLs and in progress records. Changing it orphans existing progress.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Shown to the user when choosing a tour.",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="One line on what this tour covers, shown alongside the name.",
                        max_length=255,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional icon, interpreted by the host project (a CSS class, an emoji, whatever it renders).",
                        max_length=100,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("staff", "Staff only"),
                            ("superuser", "Superusers only"),
                        ],
                        default="everyone",
                        help_text="Who is offered this tour. Enforced server-side, not just in the picker.",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to withdraw the tour without deleting it or anyone's progress.",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Sort order when several tours are offered.",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Position within the tour. Steps are shown in this order.",
                    ),
                ),
                (
                    "element",
                    models.CharField(
                        blank=True,
                        help_text="CSS selector for the element to highlight. Leave blank for a centred step with no anchor.",
                        max_length=255,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="The body of the step. HTML is allowed."
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("top", "Top"),
                            ("right", "Right"),
                            ("bottom", "Bottom"),
                            ("left", "Left"),
                            ("over", "Over the element"),
                        ],
                        help_text="Leave blank to let the renderer decide.",
                        max_length=10,
                    ),
                ),
                (
                    "align",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("start", "Start"),
                            ("center", "Center"),
                            ("end", "End"),
                        ],
                        help_text="Leave blank to let the renderer decide.",
                        max_length=10,
                    ),
                ),
                (
                    "url_name",
                    models.CharField(
                        blank=True,
                        help_text="Django URL name of the page this step lives on, for example 'quests:quests'. Preferred over a literal path, since it survives URL restructuring.",
                        max_length=255,
                    ),
                ),
                (
                    "url_args",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Positional arguments for the URL name, if it takes any.",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        help_text="Literal relative path, for example '/settings/'. Use only for pages with no URL name. Must not include a scheme or host, so that the tour works on any domain.",
                        max_length=255,
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="tourguide.tour",
                    ),
                ),
            ],
            options={
                "ordering": ["tour", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tour", "order"),
                        name="tourguide_step_unique_order_per_tour",
                    )
                ],
            },
        ),
    ]
