# Generated by Django 5.2.17 on 2026-08-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourguide", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="import_checksum",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Fingerprint of this tour as `loadtours` last wrote it. Blank for a tour written by hand.",
                max_length=64,
            ),
        ),
    ]
