# Generated by Django 5.2.17 on 2026-08-06 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TourProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tour_slug",
                    models.SlugField(
                        help_text="Slug of the tour this progress belongs to. Not a foreign key: the tour may live in another schema.",
                        max_length=100,
                    ),
                ),
                (
                    "last_step",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of the step the user last reached, so a tour spanning several pages can resume.",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the user reached the end of the tour.",
                        null=True,
                    ),
                ),
                (
                    "dismissed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the user closed the tour early. Kept separate from completion, since finishing and giving up are different outcomes.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "tour progress",
                "ordering": ["user", "tour_slug"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "tour_slug"),
                        name="tourguide_progress_one_record_per_user_and_tour",
                    )
                ],
            },
        ),
    ]
